<?php

/**
 * Implements hook_cron().
 *
 * Takes scheduled sending emails 
 */
//function gusev_mailing_cron() {
//    gusev_mailing_sending_email_from_mails_list();
//}

/**
 * Implements hook_cronapi().
 * Takes scheduled sending emails 
 */
function gusev_mailing_cronapi() {
    $items = array();
    $items['gusev_mailing_sending_emails_cron_job'] = array(
        'scheduler' => array(
            'name' => 'crontab',
            'crontab' => array(
                'rules' => array('* * * * *'),
            ),
        )
    );
    return $items;
}

/**
 * The callback for the cron job,
 */
function gusev_mailing_sending_emails_cron_job($job) {
    gusev_mailing_sending_email_from_mails_list();
}

function gusev_mailing_sending_email_from_mails_list($count_emails = 100) {
    $mails = db_select('gusev_mailing_mails_list', 'ml')
            ->fields('ml', array('mid', 'mail_from', 'mail_to', 'subject', 'body'))
            ->range(0, $count_emails)
            ->orderBy('ml.mid', 'DESC')
            ->execute()
            ->fetchAll();
    foreach ($mails as $value) {
        $to = $value->mail_to;
        $body = $value->body;
        $subject = $value->subject;
        $from = $value->mail_from;
        $mail_true = gusev_mailing_send_mail($to, $body, $subject, $from);
        if ($mail_true === TRUE) {
            db_delete('gusev_mailing_mails_list')
                    ->condition('mid', $value->mid)
                    ->execute();
        }
    }
}

function gusev_mailing_send_mail($to, $body, $subject = NULL, $from = NULL) {
    $module = 'gusev_mailing';
    $key = 'gusev_mailing_mail';
    
    if(!$from){
        $from = variable_get('site_mail', '');
    }
    $language = 'ru'; //язык
    $params = array();
    $send = FALSE; //не отправляем письмо сразу
    $message = drupal_mail($module, $key, $to, $language, $params, $from, $send); // формируем сообщение
    $message['subject'] = $subject;
    $message['body'] = array();
    $message['body'][] = $body;
    $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
    $system = drupal_mail_system($module, $key);
    $message = $system->format($message);
    // Отправляем письмо
    return $system->mail($message);
}
